### ISSUE TITLE
Cloud key not found

### ISSUE THREAD

**Issue by moh1122** [jakob-stoeck/speechToText#1]
Hello
Amazing project can you please let me know how to add a cloud key?

**Comment by jakob-stoeck** [comment]
You’re right that should be in the docs. Add the following to the `Info.plist` in between the `<dict>` and `</dict>`:

```xml
	<key>CloudSpeechApiKey</key>
	<string>YOUR_GOOGLE_CLOUD_SPEECH_KEY</string>
```
